### ISSUE TITLE
JitStatsCollector throwing errors under load

### ISSUE THREAD

**Issue by djluck** [djluck/prometheus-net.DotNetRuntime#8]
```
System.ArgumentOutOfRangeException: Counter value cannot decrease.
Parameter name: increment
   at Prometheus.Counter.Child.Inc(Double increment) in d:\a\1\s\Prometheus.NetStandard\Counter.cs:line 29
   at Prometheus.DotNetRuntime.StatsCollectors.JitStatsCollector.ProcessEvent(EventWrittenEventArgs e) in C:\dev\prometheus-net.DotNetRuntime\src\prometheus-net.DotNetRuntime\StatsCollectors\JitStatsCollector.cs:line 71
   at Prometheus.DotNetRuntime.DotNetEventListener.OnEventWritten(EventWrittenEventArgs eventData) in C:\dev\prometheus-net.DotNetRuntime\src\prometheus-net.DotNetRuntime\DotNetEventListener.cs:line 41
```

**Comment by djluck** [comment]
Will be resolved by fixes in .NET core 3.0.
